spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacy_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update

app.branch-name=Nha Thuoc So 1
app.hotline=1900xxxx
pharmacy.vat-rate=10